Globomantics/Controllers/ConferenceController.cs
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace Globomantics.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly IConferenceService conferenceService;
        public ConferenceController(IConferenceService conferenceService)
        {
            this.conferenceService = conferenceService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Conferences";
            return View( await conferenceService.GetAll());
        }

        public IActionResult Add()
        {
            ViewBag.Title = "Add Conference";
            return View(new ConferenceModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(ConferenceModel model)
        {
            if (ModelState.IsValid)
                await conferenceService.Add(model);
            return RedirectToAction("Index");
        }
    }
}

Globomantics/Controllers/ProposalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using Shared;

namespace Globomantics.Controllers
{
    public class ProposalController : Controller
    {
        IConferenceService conferenceService;
        IProposalService proposalService;
        public ProposalController(IConferenceService conferenceService, IProposalService proposalService)
        {
            this.conferenceService = conferenceService;
            this.proposalService = proposalService;
        }
        public async Task<IActionResult> Index(int conferenceId)
        {
            var conference = await conferenceService.GetById(conferenceId);
            ViewBag.Title = $"Proposals For Conference {conference.Name} " +
                $"{conference.Location}";
            ViewBag.ConferenceId = conferenceId;
            return View( await proposalService.GetAll(conferenceId));
        }

        public IActionResult Add( int conferenceId)
        {
            ViewBag.Title = "Add Proposal";
            return View(new ProposalModel { ConferenceId = conferenceId });
        }

        [HttpPost]
        public async Task<IActionResult> Add ( ProposalModel proposal)
        {
            if (ModelState.IsValid)
                await proposalService.Add(proposal);
            return RedirectToAction("Index",
                new { conferenceId = proposal.ConferenceId });
        }

        public async Task<IActionResult> Approve(int proposalId)
        {
            var proposal = await proposalService.Approve(proposalId);
            return RedirectToAction("Index",
                new { conferenceId = proposal.ConferenceId });
        }
    }
}

Globomantics/ViewComponents/StatisticsViewComponent.cs
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Globomantics.ViewComponents
{
    public class StatisticsViewComponent : ViewComponent
    {
        private readonly IConferenceService service;

        public StatisticsViewComponent(IConferenceService service)
        {
            this.service = service;
        }

        public async Task<IViewComponentResult> InvokeAsync(string statsCaption) 
        {
            ViewBag.Caption = statsCaption;
            return View(await service.GetStatistics());
        }
    }
}

Globomantics/Views/Conference/Add.cshtml
@model Shared.ConferenceModel

    <form asp-action="Add">
        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" asp-for="Name" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="Location"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" asp-for="Location" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="Start"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" type="date" asp-for="Start" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="AttendeeTotal"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" type="number" asp-for="AttendeeTotal" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-offset-2">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </div>
    </form>

Globomantics/Views/Conference/DisplayTemplates/ConferenceModel.cshtml
@using Globomantics
@using Microsoft.Extensions.Options
@model  Shared.ConferenceModel
@inject IOptions<GlobomanticsOptions> options

    <tr>
        <td>@Model.Name</td>
        <td>@Model.Location</td>
        <td>@Model.Start.ToString("ddd d MMM")</td>
        @if (Model.AttendeeTotal > options.Value.BoldConferenceAttendeeThreshold)
        {
            <td><strong>@Model.AttendeeTotal</strong></td>
        }
        else
        {
            <td>@Model.AttendeeTotal</td>
        }
        <td>
            <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@Model.Id">
                Proposals
            </a>
        </td>
    </tr>

Globomantics/Views/Conference/Index.cshtml
@model IEnumerable<Shared.ConferenceModel>
<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        @await Component.InvokeAsync("Statistics", new { statsCaption = "Statistics"})
    </div>
    <div class="col-md-4">
        <a asp-action="Add">Add</a>
    </div>
</div>

Globomantics/Views/Proposal/Add.cshtml
@model Shared.ProposalModel

    <form asp-action="Add">
        <input type="hidden" asp-for="ConferenceId" />

        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="Title"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" asp-for="Title" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="Speaker"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" asp-for="Speaker" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-2 col-md-offset-2">
                <label asp-for="Approved"></label>
            </div>
            <div class="col-md-2">
                <input class="form-control" type="checkbox" asp-for="Approved" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-offset-2">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </div>
    </form>

Globomantics/Views/Proposal/DisplayTemplates/ProposalModel.cshtml
@model Shared.ProposalModel

<tr>
    <td>@Model.Title</td>
    <td>@Model.Speaker</td>
    <td>
        @if ( Model.Approved)
        {
            <div>Yes</div>
        }
    </td>
    <td>
        @if (!Model.Approved)
        {
            <a asp-action="Approve" asp-route-proposalId="@Model.Id">Approve</a>
        }
    </td>
</tr>

Globomantics/Views/Proposal/Index.cshtml
@model IEnumerable<Shared.ProposalModel>

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Speaker</th>
                <th>Approved</th>
                <th>Actions</th>
            </tr>
            @Html.DisplayForModel()
        </table>
        <a asp-action="Add" asp-route-conferenceId="@ViewBag.ConferenceId">Add</a>
    </div>
</div>

Globomantics/Views/Shared/Components/Statistics/Default.cshtml
@model Shared.StatisticsModel
<div class="small">
    <div class="row statTitle">@ViewBag.Caption</div>
    <div class="row">
        <div class="col-md-8">Average:</div>
        <div class="col-md-4">@Model.AverageConferenceAttendees</div>
    </div>
    <div class="row">
        <div class="col-md-8">Total:</div>
        <div class="col-4">@Model.NumberOfAttendees</div>
    </div>
</div>

Globomantics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <environment include="Development">
        <link rel="stylesheet" asp-href-include="css/*" asp-fallback-href-exclude="css/all.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="css/all.min.css" />
    </environment>
    
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <img asp-append-version="true" alt="logo" src="~/img/racing.png" />
            </div>
            <div class="col-md-10 titlecol">
                <span class="title">@ViewBag.Title</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>